Fix wxGridSizer error when adding Speech plugin action
Before this change adding the "Text to speech" action causes the following
error:

PyAssertionError: C++ assertion "Assert failure" failed at
..\..\src\common\sizer.cpp(1401) in wxGridSizer::DoInsert(): too many
items (9 > 2*4) in grid sizer (maybe you should omit the number of
either rows or columns?)

I have no clue what the reason is for this error but setting the rows
argument to 0 causes FlexGridSizer to automatically set the value and
the error no longer occurs.